name: Metrics

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.contributions.svg
          base: ""
          plugin_repositories: yes
          repositories_affiliations: CONTRIBUTOR
          repositories_skipped: "y0usaf/*"
          repositories_batch: 10
